/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Account {
  'created' : Time,
  'planId' : [] | [string],
  'fullName' : string,
  'email' : string,
  'passwordHash' : string,
}
export type AdminLoginResponse = { 'failure' : string } |
  { 'success' : SessionToken };
export type SessionToken = bigint;
export type Time = bigint;
export type UserLoginResponse = { 'failure' : string } |
  { 'success' : [] | [string] };
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createAccount' : ActorMethod<
    [string, string, string, [] | [string]],
    string
  >,
  'getAccountStatistics' : ActorMethod<[], { 'totalAccounts' : bigint }>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'healthCheck' : ActorMethod<[], { 'status' : string, 'timestamp' : Time }>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'listAllAccounts' : ActorMethod<[], Array<Account>>,
  'login' : ActorMethod<[string, string], UserLoginResponse>,
  'loginAdmin' : ActorMethod<[string, string], AdminLoginResponse>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'validateAdminSession' : ActorMethod<[SessionToken], boolean>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];